version: '3'

services:
  # TODO: Dockerize for production
  appointments:
    build: .
    ports:
      - 3000:3000
    command: foreman start
    environment:
      - DB_HOST=db
    depends_on:
      - db
  db:
    build: ./docker/postgres/
    ports:
      - 5432:5432
    volumes:
      - appointments_db:/var/lib/postgresql/data:rw
    environment:
      # TODO: handle with database.yml
      - DB_NAME=${DB_NAME}
volumes:
  appointments_db:
    driver: local
