default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # TODO refactor
  host: 172.22.0.2
  username: postgres
  timeout: 5000

development:
  <<: *default
  database: appointments_development

test:
  <<: *default
  database: appointments_test

production:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: appointments
